/**
 * Variant-family data for the Inspector — moved verbatim from the
 * previous monolithic `Inspector.tsx`. Pure data, no logic changes.
 */

export const VALID_VARIANT_FAMILIES: Record<string, string[]> = {
  // Lighting
  bulb: [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'bulb-incandescent': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'bulb-halogen': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'bulb-cfl': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'bulb-smart-rgb': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'led-downlight': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],
  'tube-light': [
    'bulb',
    'bulb-incandescent',
    'bulb-halogen',
    'bulb-cfl',
    'bulb-smart-rgb',
    'led-downlight',
    'tube-light',
  ],

  // Protection Breakers & Isolators
  mcb: ['mcb', 'mcb-type-c', 'mcb-type-d', 'mccb', 'rcd', 'rcbo', 'fuse', 'spd', 'isolator-switch'],
  'mcb-type-c': [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],
  'mcb-type-d': [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],
  mccb: [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],
  rcd: ['mcb', 'mcb-type-c', 'mcb-type-d', 'mccb', 'rcd', 'rcbo', 'fuse', 'spd', 'isolator-switch'],
  rcbo: [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],
  fuse: [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],
  spd: ['mcb', 'mcb-type-c', 'mcb-type-d', 'mccb', 'rcd', 'rcbo', 'fuse', 'spd', 'isolator-switch'],
  'isolator-switch': [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'fuse',
    'spd',
    'isolator-switch',
  ],

  // Outlets
  'socket-2pin': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'socket-3pin': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'double-socket': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'switched-socket': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'socket-usb': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'socket-gfci': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],
  'socket-industrial': [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'switched-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
  ],

  // Switches
  'single-way-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'two-way-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'intermediate-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'double-pole-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'double-gang-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'push-button': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'rotary-selector-switch': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'cooker-unit': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],
  'fused-spur': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'double-gang-switch',
    'push-button',
    'rotary-selector-switch',
    'cooker-unit',
    'fused-spur',
  ],

  // Transformers
  'transformer-8v': [
    'transformer-8v',
    'transformer-12v',
    'transformer-24v',
    'step-up-down-transformer',
  ],
  'transformer-12v': [
    'transformer-8v',
    'transformer-12v',
    'transformer-24v',
    'step-up-down-transformer',
  ],
  'transformer-24v': [
    'transformer-8v',
    'transformer-12v',
    'transformer-24v',
    'step-up-down-transformer',
  ],
  'step-up-down-transformer': [
    'transformer-8v',
    'transformer-12v',
    'transformer-24v',
    'step-up-down-transformer',
  ],

  // Relays
  'relay-spst': ['relay-spst', 'relay-spdt', 'relay-dpdt', 'control-relay', 'smart-relay'],
  'relay-spdt': ['relay-spst', 'relay-spdt', 'relay-dpdt', 'control-relay', 'smart-relay'],
  'relay-dpdt': ['relay-spst', 'relay-spdt', 'relay-dpdt', 'control-relay', 'smart-relay'],
  'control-relay': ['relay-spst', 'relay-spdt', 'relay-dpdt', 'control-relay', 'smart-relay'],
  'smart-relay': ['relay-spst', 'relay-spdt', 'relay-dpdt', 'control-relay', 'smart-relay'],

  // Contactors
  contactor: ['contactor-1p', 'contactor-2p', 'contactor-3p', 'contactor-4p'],
  'contactor-1p': ['contactor-1p', 'contactor-2p', 'contactor-3p', 'contactor-4p'],
  'contactor-2p': ['contactor-1p', 'contactor-2p', 'contactor-3p', 'contactor-4p'],
  'contactor-3p': ['contactor-1p', 'contactor-2p', 'contactor-3p', 'contactor-4p'],
  'contactor-4p': ['contactor-1p', 'contactor-2p', 'contactor-3p', 'contactor-4p'],

  // Fans
  'ceiling-fan': ['ceiling-fan', 'extractor-fan', 'industrial-exhaust-fan', 'table-fan'],
  'extractor-fan': ['ceiling-fan', 'extractor-fan', 'industrial-exhaust-fan', 'table-fan'],
  'industrial-exhaust-fan': ['ceiling-fan', 'extractor-fan', 'industrial-exhaust-fan', 'table-fan'],
  'table-fan': ['ceiling-fan', 'extractor-fan', 'industrial-exhaust-fan', 'table-fan'],

  // Timers
  'timer-switch': [
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'delay-timer',
  ],
  'digital-weekly-timer': [
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'delay-timer',
  ],
  'staircase-timer': [
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'delay-timer',
  ],
  'countdown-timer': [
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'delay-timer',
  ],
  'delay-timer': [
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'delay-timer',
  ],

  // Thermostats
  thermostat: ['thermostat', 'room-thermostat', 'heating-thermostat'],
  'room-thermostat': ['thermostat', 'room-thermostat', 'heating-thermostat'],
  'heating-thermostat': ['thermostat', 'room-thermostat', 'heating-thermostat'],

  // Sensors
  'pir-sensor': ['pir-sensor', 'photocell-sensor', 'temperature-sensor', 'door-sensor'],
  'photocell-sensor': ['pir-sensor', 'photocell-sensor', 'temperature-sensor', 'door-sensor'],
  'temperature-sensor': ['pir-sensor', 'photocell-sensor', 'temperature-sensor', 'door-sensor'],
  'door-sensor': ['pir-sensor', 'photocell-sensor', 'temperature-sensor', 'door-sensor'],

  // Sounders
  bell: ['bell', 'electric-buzzer', 'wireless-doorbell', 'alarm-siren'],
  'electric-buzzer': ['bell', 'electric-buzzer', 'wireless-doorbell', 'alarm-siren'],
  'wireless-doorbell': ['bell', 'electric-buzzer', 'wireless-doorbell', 'alarm-siren'],
  'alarm-siren': ['bell', 'electric-buzzer', 'wireless-doorbell', 'alarm-siren'],

  // Motors
  motor: ['motor', 'motor-3phase', 'water-pump'],
  'motor-3phase': ['motor', 'motor-3phase', 'water-pump'],
  'water-pump': ['motor', 'motor-3phase', 'water-pump'],

  // Heaters
  'space-heater': ['space-heater', 'water-heater', 'heating-element'],
  'water-heater': ['space-heater', 'water-heater', 'heating-element'],
  'heating-element': ['space-heater', 'water-heater', 'heating-element'],

  // Distribution Boards
  'distribution-board': ['distribution-board', 'distribution-box', 'distribution-board-3phase'],
  'distribution-box': ['distribution-board', 'distribution-box', 'distribution-board-3phase'],
  'distribution-board-3phase': [
    'distribution-board',
    'distribution-box',
    'distribution-board-3phase',
  ],
};
